[package]
name = "factorio-cacher"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
bytes = "1.0"
zip = "2.0"
miniz_oxide = "0.8"
zstd = "0.13"
blake3 = "1.0"
hashlink = "0.9"
anyhow = "1.0"
bitflags = "2.0"
crc = "3.0"
